/**
 * SMS Fusion API
 * This is the SMS Fusion API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@smsfusion.com.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class HLRCallback (
  /* Unique ID for response */
  id: String,
  /* The MSISDN of the number queried */
  msisdn: Long,
  /* Short status code of the response */
  status: String,
  /* ISO 3166-2 country code */
  country: String,
  /* The operator attached to the MSISDN */
  operator: String,
  /* MCC and MNC of MSDISDN */
  mccmnc: Integer,
  /* If the response code is temporary or permenant */
  duration: String,
  /* Full status code of the response */
  message: String,
  /* Extended explanation of the status code */
  extended: String,
  /* Cost of the response */
  cost: Float
)
