/**
 * SMS Fusion API
 * This is the SMS Fusion API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@smsfusion.com.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class HLRResult (
  status: String,
  success: List[Long],
  failure: List[Long],
  /* Cost of the response */
  cost: Float,
  /* Callback URL provided */
  callback: String
)
